language: node_js
node_js:
  - "8"
before_script:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.7.0
  - export PATH="$HOME/.yarn/bin:$PATH"
  - npm install -g gulp-cli
cache:
  yarn: true
script: yarn start